version: "3"

services:
  api:
    image: node:8.11.3
    depends_on:
      - mongo
    restart: always
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      NODE_PORT: 3000
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: adm12345
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "yarn start"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: adm12345
    volumes:
      - ./dbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adm12345
